### ISSUE TITLE
Can't 'Accept' on token_request.py

### ISSUE THREAD

**Issue by ethanopp** [turing-complet/python-ouraring#19]
Running the token_request.py manually and I get to the auth screen, but when I select 'Accept' nothing happens...

Using the script exactly as is and passing client_id and secret

...What should redirect URI be set to for just using this script?

**Comment by ethanopp** [comment]
Disregard... Had to switch from https://localhost to http://localhost

**Comment by turing-complet** [comment]
Cool, glad it ended up working for you.
